### ISSUE TITLE
bot is working but its not responding....

### ISSUE THREAD

**Issue by temporhodes** [AginSquash/UnionChannel_tg#2]
Hi.
the bot is working and forwarding messages...
but it doesnt respond in bot chat ...
please check.

thanks.

**Comment by AginSquash** [comment]
Hi!
Just checked and everything works well (at least at first glance). Can you send a log file or show what the terminal outputs?
Also, please make sure that you set the correct value in **config.py** for **admin_chat_id** and **channel_id**

P.S. I almost forgot! You need to run it separately main.py (message forwarding) and ChannelControllerBot.py (bot for management)
